version: "2.1"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=fizzbuzz_twitterbot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./misc/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root"]
  fizzbuzz-twitterbot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
